table Date
	lineageTag: 95ee9294-10b2-4f13-b9c3-b9a8775dcb91

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2df0955d-0bd2-4a4f-a693-64784c81ca89
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7b9827f8-455b-4d90-8f76-f8ab0bb01085
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 88371ba8-2389-41b4-a22f-bcb756732d3b
			defaultHierarchy: LocalDateTable_1635aca9-f5cf-4673-8bd0-6cbe59eca959.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1968792-0be4-44ab-a4ea-bd4660234ee2
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: 586c9eeb-fe2f-431d-a8c4-9723ce217f20
			defaultHierarchy: LocalDateTable_d1146ef7-6f90-4647-b97e-2ffae90ba854.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3471bbd6-6da2-44e6-8388-539d2f836aa8
		summarizeBy: count
		sourceColumn: MonthKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fiscal_Year
		dataType: string
		lineageTag: ac47e60b-dea4-4eef-8679-854e4d00484f
		summarizeBy: none
		sourceColumn: Fiscal_Year

		annotation SummarizationSetBy = Automatic

	column Fiscal_Quarter
		dataType: string
		lineageTag: f588cc77-1d93-45e8-af1d-0705a18bf7a9
		summarizeBy: none
		sourceColumn: Fiscal_Quarter

		annotation SummarizationSetBy = Automatic

	column Full_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f881c1e-ddc6-4b65-93da-2377b66e228a
		summarizeBy: none
		sourceColumn: Full_Date

		variation Variation
			isDefault
			relationship: 64226bf6-de2a-49b4-9b8c-a66e436c1cc9
			defaultHierarchy: LocalDateTable_8d28e1e0-f697-4aa5-a433-1aacf469eecb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	hierarchy Fiscal
		lineageTag: 2afdb215-375e-4ac4-9ba4-7541cab5d927

		level Month
			lineageTag: 16d7fd9e-a8d1-4028-bed0-a9a5d4f6cccd
			column: Month

		level Date
			lineageTag: ce9f58fc-7722-402e-8ba2-b88ac1b588b3
			column: Date

	partition Date-e73647eb-1ddf-4b64-b31e-61b185515f84 = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("<your-workspace-url>", "/sql/1.0/warehouses/<your-warehouse-id>", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    pbi_dashboards_Database = Source{[Name="pbi_dashboards",Kind="Database"]}[Data],
				    dashboard_adventureworks_Schema = pbi_dashboards_Database{[Name="dashboard_adventureworks",Kind="Schema"]}[Data],
				    Date_Table = dashboard_adventureworks_Schema{[Name="date_data",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Date_Table,{{"DateKey", Int64.Type}, {"Date", type date}, {"Fiscal_Year", type text}, {"Fiscal_Quarter", type text}, {"Month", type date}, {"Full_Date", type date}, {"MonthKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

